### PR TITLE
volume lifecycle fixes

### LINKED ISSUE #290: support publishing multiple times and staging exactly once
The driver has traditionally supported publishing multiple times in parallel. That was overlooked when adding a single boolean for `IsPublished`: https://github.com/kubernetes-csi/csi-driver-host-path/blob/7a252595fe60ac7a75fed45214430893aff46d18/pkg/state/state.go#L53

That must be a list of target paths.

### PR DESCRIPTION
**Pull request by pohly**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

The [recently introduced support for tracking of staging and publishing](https://github.com/kubernetes-csi/csi-driver-host-path/pull/260) can be improved:
- Now it properly supports publishing more than once.
- Mutex locking in NodeStageVolume and NodeUnstageVolume was missing.
- NodeUnstageVolume and NodeUnpublishVolume can bail out early
      when nothing needs to be done. In the case of NodeUnpublishVolume
      that avoids unmounting at a path not managed by the driver. The
      driver cannot distinguish between an invalid path and an idempotent
      call, so this is not treated as an error.
- NodePublishVolume checks that the staging target path is valid.
- NodeStageVolume rejects staging more than once.

**Which issue(s) this PR fixes**:
Fixes #290 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
The code that gets enhanced was in no prior release, therefore we don't need to mention this change.
```release-note
NONE
```

### CODE REVIEW

**Comment by pohly** [comment]
@avalluri : can you perhaps review?

File: pkg/state/state.go [hunk 1]
```diff
@@ -48,9 +48,14 @@ type Volume struct {
 	NodeID         string
 	Kind           string
 	ReadOnlyAttach bool
-	IsAttached     bool
-	IsStaged       bool
-	IsPublished    bool
+	Attached       bool
```
Comment (pohly) [inline pkg/state/state.go:51]: I removed the `Is` prefix for consistency with the other booleans and because it no longer works for the fields that aren't a boolean anymore.

**Review by avalluri — APPROVED** [review]
Looks good to me.
