### PR TITLE
Fix cp arg expansion bug in cloning implementation

### LINKED ISSUE #81: Using `*` in cp commands is a bad idea
Passing `cp -a /csi-data-dir/xxxx/*` on some shells will actually attempt to try and find a file named `*` to copy.  We should instead be using the cp specific syntax and using `/.` instead.

### PR DESCRIPTION
**Pull request by j-griffith**
**What type of PR is this?**

bug

**What this PR does / why we need it**:

The clone implementation is just using `cp /*` can result in trying to actually find/copy a file named `*`.  The result in some container images is a stat error for no such file or directory.  Instead we should be using the cp notation of `/.` so we're portable and always work.

**Which issue(s) this PR fixes**:

Fixes #81

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

File: pkg/hostpath/hostpath.go [hunk 1]
```diff
@@ -293,7 +293,7 @@ func loadFromVolume(srcVolumeId, destPath string) error {
 
 	// If the source hostpath volume is empty it's a noop and we just move along, otherwise the cp call will fail with a a file stat error DNE
 	if !isEmpty {
-		args := []string{"-a", srcPath + "/*", destPath + "/"}
+		args := []string{"-a", srcPath + "/.", destPath + "/"}
```
Comment (msau42) [inline pkg/hostpath/hostpath.go]: do you need -R?

Comment (j-griffith) [reply pkg/hostpath/hostpath.go]: Nah, `-a` is the equivalent of `-dR`
